DROP TABLE USER_INFO;
DROP TABLE REST_USER_INFO;

CREATE TABLE USER_INFO (
 USER_ID VARCHAR(32) PRIMARY KEY,
 REST_FLAG VARCHAR(1) DEFAULT 'N',
 CREATE_DATE TIMESTAMP
);

CREATE INDEX IX_USER_INFO_01 ON USER_INFO (CREATE_DATE);

CREATE TABLE REST_USER_INFO (
 USER_ID VARCHAR(32) PRIMARY KEY,
 CREATE_DATE TIMESTAMP
);

CREATE INDEX IX_REST_USER_INFO_01 ON REST_USER_INFO (CREATE_DATE);
